### ISSUE TITLE
correctness of this script regarding version suffix strings and location of hphpize

### ISSUE THREAD

**Issue by rrh** [hhvm/packaging#107]
I'm experimenting with running https://github.com/hhvm/packaging locally

Is this script in actual use?  I'm a little confused, since there's an assumption about the structure of version names here, namely version strings optionally end with -dbg or -dev:
  https://github.com/hhvm/packaging/blob/master/hhvm/deb/package#L54
but the generator of this info
  https://github.com/facebook/hhvm/blob/master/hphp/runtime/base/program-functions.cpp#L1393
generates something ending with ' (dbg)' (eg space open paren dbg close paren)

There's also some suspicion since it it checking for the existence of $BUILD/usr/bin/hphpize but hphpize is normally installed in /usr/local/bin

**Comment by paulbiss** [comment]
We do run this internally for both our nightly builds via crontab and for our release builds manually. The version name is passed in as an [argument](https://github.com/hhvm/packaging/blob/master/hhvm/deb/package#L19) and doesn't need to match the one output by the version option to hhvm.

**Comment by jwatzman** [comment]
We do [check that the version minimally makes sense](https://github.com/hhvm/packaging/blob/master/hhvm/deb/package#L154-L165), but yeah it's a specified parameter and not pulled out of HHVM.

This entire script is kind of sketchy and hacked together. It's also designed to run on a "build machine" which is just a Mac Pro hosting a ton of VMs, that is sitting under someone's desk. @paulbiss has been looking into what needs to happen to get package builds running on real FB infra, with real CI, testing, etc etc. (And more than one simultaneous build on a poor overburdened Mac Pro!) So it's likely this script is going to be rewritten or severely gutted in the next few months.

**Comment by jwatzman** [comment]
That said, it still is the script we use today, so if you have any questions, bugs, PRs, etc, happy to take a look.

**Comment by rrh** [comment]
Is it safe to assume that this script is only run on an ubuntu machine, or on a linux machine?  It currently runs sed with the -E flag, which, AFAICT, only exists as such on macosx.

**Comment by jwatzman** [comment]
Yeah, it's the deb packaging script, it needs to run on the OS we're packaging for, so I think an assumption of a system that uses debs (i.e., Debian, Ubuntu, and Mint) is safe.

**Comment by fredemmott** [comment]
Closing: we stopped using this script last year.
