### ISSUE TITLE
eager commits to packaging repo

### ISSUE THREAD

**Issue by rrh** [hhvm/packaging#109]
It seems odd that this directory and contents are even part of the packaging repository
  https://github.com/hhvm/packaging/tree/master/hhvm/deb/skeleton/var/run/hhvm

Among other things, a system wide purge of any files hhvm.hhbc will result in git later squawking about this file being missing from its purview.

**Comment by jwatzman** [comment]
Yeah -- I think the idea was to make sure the files exist, but like this, along with the problem you mention, it will overwrite them on every upgrade :\

Something might require this *directory* to exist, but the postinst script can do that easily enough if needed. I'll look into it when I get some time.
