### ISSUE TITLE
Ubuntu apt repository broken?

### ISSUE THREAD

**Issue by df-jablan** [hhvm/packaging#114]
After following the directions to add  the hhvm to my /etc/apt/sources.list.d/hhvm.list and running the update, I get the following:

```
$ sudo apt-get install hhvm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package hhvm
```

Everything is configured properly. 

What I discovered is that there are no i386 packages listed on the repos. Is this intentional or a build issue?

**Comment by jwatzman** [comment]
> What I discovered is that there are no i386 packages listed on the repos.

HHVM is only supported on 64-bit systems.

Are you on a 64-bit system? Did you do `sudo apt-get update` first?

**Comment by jwatzman** [comment]
No response, closing.
