### ISSUE TITLE
Packages for Ubuntu 15.04 vivid?

### ISSUE THREAD

**Issue by joshuataylor** [hhvm/packaging#119]
Hi,

Ubuntu 15.04 came out last month, and would be awesome to have packages for it created.

**Comment by jwatzman** [comment]
Yep, just need to find time to set up a VM on our build machine.

**Comment by joshuataylor** [comment]
Awesome, lots of changes in 15.04... Hopefully it won't be such a PITA for
15.10 and onwards for a while.

**Comment by jwatzman** [comment]
Thankfully I don't think the changes affected us much :) The existing build script worked just fine and the new debian control files were straightforward (they're already committed).

**Comment by hyperfocus1337** [comment]
When are you going to update the wiki for Ubuntu 15.04? https://github.com/facebook/hhvm/wiki/Prebuilt-packages-on-Ubuntu-15.04-%28vivid%29

**Comment by jwatzman** [comment]
Whenever the packages are ready.

**Comment by jwatzman** [comment]
`hhvm-nightly` is now available for vivid and I've updated the wiki page. `hhvm` should be available shortly (I'm building 3.7.0 now, should take about an hour to show up); debug packages will show up sometime later.

**Comment by joshuataylor** [comment]
Awesome, thanks so much @jwatzman :+1:

**Comment by joshuataylor** [comment]
It seems hhvm-dev-nightly also installs hhvm? Is this 

$ sudo apt-get install hhvm-dev-nightly
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  hhvm
The following NEW packages will be installed:
  hhvm hhvm-dev-nightly
0 to upgrade, 2 to newly install, 0 to remove and 15 not to upgrade.
Need to get 0 B/20.1 MB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package hhvm.
(Reading database ... 231007 files and directories currently installed.)
Preparing to unpack .../hhvm_3.7.0~vivid_amd64.deb ...
Unpacking hhvm (3.7.0~vivid) ...
Selecting previously unselected package hhvm-dev-nightly.
Preparing to unpack .../hhvm-dev-nightly_2015.05.07~vivid_amd64.deb ...
Unpacking hhvm-dev-nightly (2015.05.07~vivid) ...
Processing triggers for systemd (219-7ubuntu4) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up hhvm (3.7.0~vivid) ...
********************************************************************
* HHVM is installed.
*
* Running PHP web scripts with HHVM is done by having your
* webserver talk to HHVM over FastCGI. Install nginx or Apache,
* and then:
* $ sudo /usr/share/hhvm/install_fastcgi.sh
* $ sudo /etc/init.d/hhvm restart
* (if using nginx)  $ sudo /etc/init.d/nginx restart
* (if using apache) $ sudo /etc/init.d/apache restart
*
* Detailed FastCGI directions are online at:
* https://github.com/facebook/hhvm/wiki/FastCGI
*
* If you're using HHVM to run web scripts, you probably want it
* to start at boot:
* $ sudo update-rc.d hhvm defaults
*
* Running command-line scripts with HHVM requires no special setup:
* $ hhvm whatever.php
*
* You can use HHVM for /usr/bin/php even if you have php-cli
* installed:
* $ sudo /usr/bin/update-alternatives \
*    --install /usr/bin/php php /usr/bin/hhvm 60
********************************************************************
Setting up hhvm-dev-nightly (2015.05.07~vivid) ...

**Comment by jwatzman** [comment]
Can you file a new issue about that? It's unrelated to vivid specifically.
