### ISSUE TITLE
can't find $DESTDIR/usr/bin/hphpize

### ISSUE THREAD

**Issue by rrh** [hhvm/packaging#123]
This code and nearby smells:
  https://github.com/hhvm/packaging/blob/master/hhvm/deb/package#L162
My build $BUILD dir (a mkdir in /tmp) has a ./usr/local/bin/hphpize but not a ./usr/bin/hphpize

I recall some changes came down the wire, either in hhvm/packaging (which I don't see on quick perusal) or in the hhvm main code, involving renaming of the directories involved with /usr/local/bin

**Comment by jwatzman** [comment]
The script, when it does its own build, passes `-DCMAKE_INSTALL_PREFIX="/usr"` to cmake -- did you do the same?

**Comment by fredemmott** [comment]
Fixed in new WIP nightly system (see https://github.com/hhvm/packaging/issues/128#issuecomment-342037825 )
