### ISSUE TITLE
hhvm-dev-x.y.z recommends hhvm, should require/recommend hhvm-x.y.z

### ISSUE THREAD

**Issue by fredemmott** [hhvm/packaging#125]
While not strictly required, it seems very strange to have hhvm-3.6.3 installed then apt-get install hhvm-dev gets me the headers for 3.7.2.

**Comment by jwatzman** [comment]
Probably a similar dependency issue to #120

**Comment by fredemmott** [comment]
Fixed in new WIP nightly system (see https://github.com/hhvm/packaging/issues/128#issuecomment-342037825 )
