### ISSUE TITLE
nightly-dev builds

### ISSUE THREAD

**Issue by steelbrain** [hhvm/packaging#126]
I am using the new anonymous shapes and the `Shapes::*` methods in my codebase now and starting to love it, but they set me back from using any extension, as that extension is compiled with `hhvm-dev` of the latest release, which makes HHVM cry because of version mismatch.
It'll be great to have nightly-dev builds so that people who like living on the edge, don't have to rebuild around the globe, every time they want to use new unreleased features.

**Comment by simonwelsh** [comment]
`hhvm-dev-nightly` already exists.

**Comment by steelbrain** [comment]
Nooooooo :sob:
