### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by semuk** [hhvm/packaging#127]
Hi

Am unable to install due to the following issues
The following packages have unmet dependencies:
 hhvm : Depends: libmemcached11 but it is not installable
        Depends: librtmp1 but it is not installable

Server Ubuntu 14.04 x64 

Ran update more than once same issue

Thanks

**Comment by jwatzman** [comment]
What line did you add to your apt sources.list? This sounds like you added one for a different distribution.

**Comment by semuk** [comment]
My mistake - I will close the issue - thanks
