### ISSUE TITLE
Provide packages for more recent distributions

### ISSUE THREAD

**Issue by md-5** [hhvm/packaging#128]
Jessie packages were provided whilst it was still testing for ages. It would be nice to have installable packages for testing in general, or at the least stretch.

Thanks.

**Comment by jwatzman** [comment]
*Maybe* in 6 months or so, but given the recent stable release of jessie, IMO testing is a huge moving target right now, basically the same as targeting sid. With jessie, even in the last few months leading up to its release, there were some major version bumps and other work that had to be done to keep the packages installable.

**Comment by mklooss** [comment]
*bump*

**Comment by N3X15** [comment]
Stretch has gone stable. https://www.debian.org/News/2017/20170617

**Comment by jr3074** [comment]
when it will support debian 9?

**Comment by fredemmott** [comment]
I've started to take a look, but it's spare-time only for now. If I don't get this done soon, I should almost certainly get this done October-December.

If I get it done soon, it'll be starting with 3.21 - 3.20 (and third-party) are not compatible with OpenSSL 1.1, but it looks like the nightlies are. While debian 9 includes 1.0 as well, several of our other dependencies require 1.1 on 9.

**Comment by fredemmott** [comment]
So the notes aren't only on my laptop:

```
git clone git@github.com:facebook/hhvm.git hhvm-nightly-2017.07.06
cd hhvm-nightly-2017.07.06
git checkout HHVM-3.20.2 # if doing release build
git submodule update --init --recursive
find . -name .git | xargs rm -rf
tar zcvf ../hhvm-nightly_2017.07.06.orig.tar.gz hhvm-nightly-2017.07.06 # Debian really cares about this naming

cd hhvm-nightly-2017.07.06
cp -R /path/to/packaging/hhvm/deb/stretch/debian debian/
apt-get install -y devscripts
sed -i 's/hhvm-nightly/hhvm/g' debian/control # if doing release
# Generate placeholder debian/changelog file
dch --create -v 2017.07.06-1~stretch --package hhvm-nightly --controlmaint --distribution stretch --force-distribution --empty
# Build a deb that depends on all the build-depends
mk-build-deps
# Install it, and dependencies
apt-get install -y ./hhvm-nightly-build-deps_2017.07.06-1~stretch_all.deb
# Remove it so that debuild doesn't complain below
rm hhvm-nightly-build-deps_2017.07.06-1~trusty_all.deb
# Build the packages
debuild -us -uc
```

webscalesqlclient in third-party needs updating to facebook/mysql-5.6#d26efe0d7763b6c9ba67a5cb42faebf075298b02 to support openssl

**Comment by fredemmott** [comment]
Also need OPENSSL_NO_SSL2 defined in HHVM itself (might end up being added to folly's openssl portability header)

**Comment by fredemmott** [comment]
hphp/runtime/ext/openssl/ext_openssl.cpp is somewhat incompatible with openssl 1.1

**Comment by fredemmott** [comment]
With diffs in flight, I have it compiling, but not linking.

**Comment by fredemmott** [comment]
Links now too.

**Comment by Neustradamus** [comment]
Any news for Debian 9 Stretch (stable) and Debian Buster (testing)?
Maybe to add unstable too?

**Comment by fredemmott** [comment]
I'm not able to spend more time on HHVM for another month or two; finishing off stretch at least is likely to be near the top of the list when I can.

That said, if you're happy to build yourself, last time I checked it will work if you update the 'webscalesql' (actually Facebook's MySQL fork nowadays) submodule in third-party/

**Comment by alex-mashin** [comment]
Still no Zesty version; what is worse, the Yakkety version will not install under Zesty because of unmet dependencies.

**Comment by Neustradamus** [comment]
http://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html

**Comment by alex-mashin** [comment]
Why is this bug closed? What has the-future-of-hhvm-as-hack-and-no-php got to do with packaging? Or is it a subtle way to say "Migrate back to PHP already"?

**Comment by fredemmott** [comment]
It's not closed, and that comment was not by a member of the team. Fixing this issue is one aspect of work on the build system I want to address by the end of the year

**Comment by fredemmott** [comment]
I have an end-to-working working package build system for stretch now, and I'm ~ 80% confident it will work for the newer versions of ubuntu too, but haven't tested.

TODO: make sure we're including all the 'extra' stuff that's included in the current packages, such as install-fastcgi.sh

**Comment by fredemmott** [comment]
![screen shot 2017-10-31 at 3 10 53 pm](https://user-images.githubusercontent.com/360927/32251310-bd1ffcb8-be4d-11e7-9044-631d83b020c3.png)


![](http://i0.kym-cdn.com/entries/icons/mobile/000/005/673/sooon.jpg)

**Comment by fredemmott** [comment]
Current state:
 - building .debs for everything in the above screenshot
 - actively working on wheezy and artful; wheezy is problematic because GCC is so old, artful is problematic because GCC is so new :p
 - except for the "figure out the right CXXFLAGS and LDFLAGS" parts, I /think/ artful is ready after https://github.com/facebook/hhvm/commit/b506902af2b7c53de6d6c92491c2086472292004

Big todo: actually publish/sign these debs in apt repos

**Comment by fredemmott** [comment]
```
-rw-r--r-- 1 root root 2.6K Nov  3 18:53 hhvm-nightly-build-deps_2017.11.03-1~artful_all.deb
-rw-r--r-- 1 root root 483M Nov  3 20:36 hhvm-nightly-dbg_2017.11.03-1~artful_amd64.deb
-rw-r--r-- 1 root root 4.7M Nov  3 20:36 hhvm-nightly-dev_2017.11.03-1~artful_amd64.deb
-rw-r--r-- 1 root root  13K Nov  3 20:36 hhvm-nightly_2017.11.03-1~artful.debian.tar.xz
-rw-r--r-- 1 root root 1.9K Nov  3 20:36 hhvm-nightly_2017.11.03-1~artful.dsc
-rw-r--r-- 1 root root 9.3M Nov  3 20:36 hhvm-nightly_2017.11.03-1~artful_amd64.build
-rw-r--r-- 1 root root 2.8K Nov  3 20:36 hhvm-nightly_2017.11.03-1~artful_amd64.changes
-rw-r--r-- 1 root root  15M Nov  3 20:36 hhvm-nightly_2017.11.03-1~artful_amd64.deb
```

Will hopefully be in tomorrow's automated builds - that's not from the 2017.11.03 tarball because that doesn't include the diff above.

**Comment by fredemmott** [comment]
- Replace `ubuntu` with `debian` in the `add-apt-repository` line below for centos support
 - new GPG key
 - `dl2.hhvm.com` is temporary, expect it to replace `dl.hhvm.com` shortly

```$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
$ apt-get install software-properties-common
$ apt-key  adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xB4112585D386EB94
$ add-apt-repository "deb http://dl2.hhvm.com/ubuntu $(lsb_release -sc) main"
$ apt-get update
$ apt-get install hhvm-nightly
$ hhvm --version
HipHop VM 3.23.0-dev (rel)
Compiler: 1509928332_512103253
Repo schema: c629dee96d45bcfcdddaf6d528359ad91000e9b6
```
