### ISSUE TITLE
HHVM and Virtualmin

### ISSUE THREAD

**Issue by ADDISON74** [hhvm/packaging#129]
I am struggling finding a manually way to replace PHP with HHVM but no chance to get a positive result. I am using an unchanged Virtualmin package in a test environment (Apache, MySQL, PHP5, ...). I got and installed HHVM in terminal, then when I tried to install it for Apache using install_fastcgi.sh I get:

  Detected enabled fcgid.load configuration, setting up integration
  Force enabling module hhvm_fcgid.conf 
  WARNING: Unsupported hhvm_fcgid, not configuring Restaring Apache

In a LAMP installation, HHVM replaces perfectly PHP, but not in Virtualmin.

Please those who managed replacing PHP with HHVM and having Apache as webserver, please give a solution. Thank you.

**Comment by jwatzman** [comment]
The HHVM team isn't super familiar with Apache configuration. You may have luck with some community-maintained docs here: https://github.com/facebook/hhvm/wiki/FastCGI
