### ISSUE TITLE
Using /var/run for hhvm.repo.central.path on Ubuntu is not a great choice

### ISSUE THREAD

**Issue by autarch** [hhvm/packaging#132]
On my Ubuntu (14.04) `/var/run` is a tmpfs mount that's only 400MB in size. The `hhvm.hhbc` file grew to a little over 350MB on one system. I think it may make more sense to default to putting this file under `/var/cache/hhvm` instead.

**Comment by jwatzman** [comment]
Sure -- want to send a PR to fix it?

**Comment by autarch** [comment]
I'll try to work on it this weekend. I just wanted to make sure that this was something you would want changed first.

**Comment by jwatzman** [comment]
cf https://github.com/hhvm/packaging/pull/134

**Comment by RavanH** [comment]
Ran into the same on a small VPS (running Debian Wheezy) where tmpfs is limited to 10% of the total available RAM per virtual server. The /var/run/hhvm/hhvm.hhbc quickly filled up all available space.

**Comment by collinbarrett** [comment]
ah, this is what I am running into [here](https://github.com/facebook/hhvm/issues/7240) as well. how can I fix this temporarily?

**Comment by Orvid** [comment]
Ah, you should be able to shutdown HHVM, then delete the .hhbc file, then start it back up, it will regenerate the bits that it needs. Each separate build of HHVM will re-compile the core systemlib and insert it into that DB. There's not currently a limit on the number of separate builds that it will put in one file.

**Comment by collinbarrett** [comment]
thanks, @Orvid . I have tried that (I think) several times and the file quickly grows back to max out my /run space. I do...

`sudo service hhvm stop`
 `sudo rm /run/hhvm/hhvm.hhbc`
`sudo service hhvm start`

And with one refresh of the WordPress back end, and one refresh of the Piwik back end (the only two PHP apps running on this server are one instance of each), the file is eating up my full 49M /run tmpfs space again.

I tried moving the repo to /var/cache via the server.ini, but it did not create the file and my sites wouldn't load. I'm wondering if it is a permissions/ownership thing?

**Comment by Orvid** [comment]
It is possible that it's a permissions issue. Perhaps try copying the hhbc that HHVM currently generates over to the cache dir and making sure the permissions are the same?

**Comment by collinbarrett** [comment]
Hmm, it ok, I could probably figure out how to make that work. But, it does seem like I'd want this database in-RAM if possible for the best speed... Trying to figure out how to resize my /run mount...

**Comment by Orvid** [comment]
It won't make a significant difference, it's loaded at startup, having the file itself permanently in RAM is actually fairly pointless.

**Comment by collinbarrett** [comment]
@Orvid hmm, ok, thanks. I was able to double my /run size per [this](https://askubuntu.com/questions/57297/why-has-var-run-been-migrated-to-run/183224#183224), so that should solve the issue for now. Will monitor the chatter about actually moving it in the future. Thanks for your help.

**Comment by collinbarrett** [comment]
@Orvid well, if it really won't make a difference, why waste the ram? I just moved it to /var/cache/hhvm and fixed the permissions/ownership. all is working now. thanks!

**Comment by collinbarrett** [comment]
actually, per this discussion, if I am going to enable RepoAuthoritative, it seems like /var/lib is better than /var/cache

**Comment by collinbarrett** [comment]
just to clarify, there should only be a single .hhvm.hhbc file in the directory specified by `hhvm.repo.central.path` in server.ini, correct? Would there be any reason that a second one would be created in my user home directory (assuming `hhvm.repo.central.path` is not set to my home directory)? I have a rather large .hhvm.hhbc in my home directory as well. When I delete it, it comes back. And when I delete the one located at `hhvm.repo.central.path`, that one comes back too. It seems like there should only be one, correct?

Thanks.

**Comment by collinbarrett** [comment]
Does HHVM maybe sync a backup of the hhvm.hhbc to the home directory every so often so that on a reboot it can load it back into /var/run (RAM) rather than recreate it?

**Comment by jwatzman** [comment]
No. I'm pretty sure the one in your home directory is from when you run CLI scripts as yourself, as opposed to the main webserver. In our default Debian ini scripts, `hhvm.repo.central.path` is only set in `server.ini`, which isn't read if you run HHVM manually on the CLI (unless you manually specify that INI file yourself too). The main webserver is told about `server.ini` by our `init.d` scripts, and so puts the HHBC repo into `/var/run`.

**Comment by collinbarrett** [comment]
@jwatzman that makes sense. that's exactly what it is. i was debugging a site from the cli yesterday, so that must have created it. thanks!

**Comment by fredemmott** [comment]
This seems to have been fixed in march.
