### ISSUE TITLE
GMP extension not included in ubuntu packages

### ISSUE THREAD

**Issue by fredemmott** [hhvm/packaging#133]
refs facebook/hhvm#6065

**Comment by paulbiss** [comment]
Looks as if this was intentional: https://github.com/hhvm/packaging/commit/d86d8036abac71997789d0a0d8753513826a3086

cc @jwatzman

**Comment by jwatzman** [comment]
I don't remember why I did this, stupid me for not having a better commit message :(

@sgolemon do you remember? I think this had to do something with the IMPLICIT/EXPLICIT extensions...

**Comment by rubensayshi** [comment]
hmm, this is pretty painful for people who rely on the prebuild packages ... will this be fixed soon?

**Comment by jwatzman** [comment]
@paulbiss was going to fix this, so that I'm not the only one that knows how to update our build machines :) But yeah, we should revert https://github.com/hhvm/packaging/commit/d86d8036abac71997789d0a0d8753513826a3086.

**Comment by apaloma** [comment]
Can we count on this being fixed in 3.10?

**Comment by jwatzman** [comment]
Yeah. Sorry it's taken so long for such a simple fix, keep forgetting.
