### ISSUE TITLE
Wily WereWolf (15.10) Packages

### ISSUE THREAD

**Issue by steelbrain** [hhvm/packaging#136]
Beep Beep

**Comment by J0WI** [comment]
+1

**Comment by Orvid** [comment]
Note that building on 15.10 currently requires explicitly using GCC 4.9, and also recompiling both boost and glog with GCC 4.9.

**Comment by jwatzman** [comment]
Oof, this GCC 5 thing is really coming to a head.

**Comment by ovr** [comment]
Any news?

**Comment by jwatzman** [comment]
It's going to be a few weeks at least before I get to this, sorry.

**Comment by nazar-pc** [comment]
So sad, every time when new version of Ubuntu is out we need to wait 1-1.5 months to use it:(

**Comment by jwatzman** [comment]
Normally, it builds out of the box, and it just takes us some time to deal with the control files and get a VM set up -- which it not a trivial process itself. But it's much less work than what is going on with 15.10, which is dealing with the GCC 5 upgrade and ABI issues, there's a lot of real work there. (Most of which I think our community has thankfully done for us, but I need to look into it.)

You are welcome to send us a PR for the GCC 5 ABI issues, and/or a PR to add a wily control file to the packaging repo. That would expedite things. :) Or you can stick with the very well supported LTS releases.

It's just a matter of our small team having time to deal with this, as opposed to working on PHP7 support, OS X support, revamping our docs, reviewing pull requests, triaging and fixing issues, crashes, and the zillion other things that are going on.

**Comment by jwatzman** [comment]
@Orvid I didn't have to do any of that, using GCC 5 seemed to work out of the box -- is there something I'm missing? I think there was a little GCC 5 compatibility work that went in, that might have been enough?

**Comment by Orvid** [comment]
Those were needed because he was trying to compile with 4.9 on 15.10, because the distro packages for boost and glog were compiled with 5.0, where there is both an ABI and name mangling change.

**Comment by jwatzman** [comment]
OK -- the system default compiler on wily is 5.1, and it seems to work out of the box if you just use 5.1 for everything (since AFAIK the system packages are all also compiled with 5.1).

Since we build with 5.1 now (we didn't used to), this makes getting wily packages together somewhat easier. Still will be a few days at the very least.

**Comment by HeikoMamerow** [comment]
GO-GO-GO! ;-)

**Comment by prakgoya** [comment]
Any updates on this?

**Comment by jwatzman** [comment]
Other than what I posted above, not yet, sorry. Been on holiday and trying to get our PHP7 support together for 3.11.

**Comment by prakgoya** [comment]
I would like to help on getting this done. Where may I start?

**Comment by jwatzman** [comment]
We need a control file first; here's the one for 15.10: https://github.com/hhvm/packaging/blob/master/hhvm/deb/vivid/DEBIAN/control -- I'd start with that, just copy-paste into a new wily directory. Then use the packaging script to build a deb **on a wily system**, then use `gdebi` to install that package **on a wily system with nothing installed beyond the base system**. Make sure it installs and runs... changing the version numbers for e.g., boost is the usual culprit here. Then send a PR with a new control file.

That's actually the easy part, when I get an hour or two I can just do it. The more annoying bit is something we have to do, actually get a VM set up to do the builds. @fredemmott had some interesting idea about using docker instead, but I don't know how hard that is or how far off it would be, probably well outside the scope of 3.11 on wily.

**Comment by jwatzman** [comment]
OK, control files are in. We just need to get a build VM set up.

**Comment by prakgoya** [comment]
I've got a build VM for the moment on my private system, but the system is giving some errors. I'll post back the errors in a day.

**Comment by jwatzman** [comment]
If you are having build issues, please do not post them here, opening an issue against the main HHVM project is the right way to report those.

**Comment by prakgoya** [comment]
Issues are not with building HHVM; it builds fine. The issues are with the creation of a package.

**Comment by jwatzman** [comment]
We have a build VM set up internally. I'm going to do a test "nightly" later this afternoon.

**Comment by jwatzman** [comment]
OK, nightly builds are set up. 3.11.0 should come out for wily once we tag and release it later this week.

**Comment by prakgoya** [comment]
Thanks for the resolution @jwatzman
