### ISSUE TITLE
Provide encrypted connection (https) to dl.hhvm.com

### ISSUE THREAD

**Issue by J0WI** [hhvm/packaging#137]
Let's encrypt the web!

**Comment by jwatzman** [comment]
This is something we'll have to take up with OSUOSL at some point. FWIW we do provide a GPG key that signs the packages.

**Comment by J0WI** [comment]
GPG is fine to check plausibility, but https gives additional privacy, because others can't see exactly what you are downloading/searching for.

**Comment by bauerj** [comment]
FWIW, one of the [repository mirrors](https://docs.hhvm.com/hhvm/installation/linux#mirrors), https://hhvm.bauerj.eu/ (:innocent:) supports HTTPS.

**Comment by fredemmott** [comment]
This is in progress, waiting for CA approval.

**Comment by fredemmott** [comment]
Done for https://dl2.hhvm.com

![screen shot 2017-11-08 at 1 19 17 pm](https://user-images.githubusercontent.com/360927/32574935-77d09e52-c487-11e7-934e-6216f9803085.png)

When 3.23 is released, I'll change dl.hhvm.com to point at dl2.hhvm.com too (the certificate is valid for both)

If you decide to use this immediately, there's also a new GPG key for the apt repositories:

https://dl2.hhvm.com/conf/hhvm.gpg.key
