### ISSUE TITLE
Xenial Xerus packages

### ISSUE THREAD

**Issue by doublecompile** [hhvm/packaging#141]
Well, the Canonical machine dropped Xenial (16.04) yesterday. 

Interestingly, they include HHVM 3.11.1 [in their universe repositories](http://packages.ubuntu.com/xenial/php/hhvm). (Weird that they'd pick a non-LTS version, though).

Can we get Xenial added to the build?

**Comment by nazar-pc** [comment]
The only problem with building HHVM on 16.04 is moved `libtbb.so` from `/usr/lib` to `/usr/lib/x86_64-linux-gnu`
https://github.com/nazar-pc/docker-build-hhvm/blob/9969f35efa996962e784230769d6dcff2bcbbc89/Dockerfile#L19

**Comment by collinbarrett** [comment]
I am trying to install HHVM on Xenial. Installing from the universe repo seems to work fine, but the install_fastcgi.sh script that I used to run for the previous prebuilt HHVM packages does not exist. Can anyone point me in the right direction to get a prebuilt that contains that script on 16.04? Or does it not exist yet?

**Comment by jwatzman** [comment]
No one from our team has been involved in the official Debian/Ubuntu packages since version 3.4 or so, so I don't know much about them other than the version that made it into 16.04 (which is version 3.11) is already out of security support on our end. I'd highly recommend upgrading to version 3.12, which unfortunately means building from source right now.

When I get time I hope to get control files for 16.04 together, but I don't know when that will be. cc @paulbiss in case he might have time, this is a fairly important distro since it's an Ubuntu LTS...

**Comment by collinbarrett** [comment]
@jwatzman ok, that's kind of what I was gathering but wanted to verify. yes, it'd definitely be good to get a pre-built for Xenial. thanks.

**Comment by davidxdunn** [comment]
Yeah, I'm definitely looking forward to a pre-built for Xenial as I'd love to do release upgrades from my 15.10's on to 16.04 prior to 15.10 becoming EOL.

**Comment by jwatzman** [comment]
I just landed the control files for xenial. Now it's just up to @paulbiss / @Orvid to get a VM up and running on the build machine :)

**Comment by davidxdunn** [comment]
Awesome news !! I have been waiting for this for all month! :)

**Comment by lbadger** [comment]
That's great news. I've spent most of yesterday trying to just get 3.12.1 to build on 16.04, but I was having to many issues. I assumed it related to the newer version of GCC I was using.

**Comment by jwatzman** [comment]
Keep in mind actually shipping packages still requires a build VM to be set up, which is easy but takes an unfortunate amount of time, and I can't speak for how busy the folks are that can do this. (From what I've talked with them recently, they are extremely busy, e.g., tracking down a nasty segfault regression in the upcoming 3.14.)

@lbadger I built off of master, but it built without any issues. See if master works for you, it should? If not maybe file an issue against HHVM.

**Comment by lbadger** [comment]
@jwatzman master seemed to build just fine thanks!

**Comment by lbadger** [comment]
@jwatzman I'm using hhvm/packaging with 3.12.2, but the xenial control files were only in the master branch. Can they be merged in to the HHVM-3.12 branch as well?

**Comment by Orvid** [comment]
We don't currently plan to release 3.12 on Xenial. 3.14 is the first version we plan on supporting on Xenial.

**Comment by doublecompile** [comment]
I just today saw the availability of HHVM 3.14 on Xenial in the repo. Thanks so much @jwatzman @Orvid @paulbiss :tada:

**Comment by collinbarrett** [comment]
In case anyone runs across this looking for the pre-built package for xenial, it is now live. HHVM docs haven't been updated yet. Installing the prebuilt using the same steps as on previous Ubuntu versions from the [install page](https://docs.hhvm.com/hhvm/installation/linux#ubuntu-14.04-trusty) works now with xenial.

https://serverfault.com/questions/778860/install-hhvm-on-ubuntu-16-04-w-install-fastcgi-sh
