### ISSUE TITLE
Ubuntu 16.04 Signature by key uses weak digest algorithm

### ISSUE THREAD

**Issue by craigcarnell** [hhvm/packaging#145]
```
W: http://dl.hhvm.com/ubuntu/dists/trusty/InRelease: Signature by key 36AEF64D0207E7EEE352D4875A16E7281BE7A449 uses weak digest algorithm (SHA1)
```

**Comment by Orvid** [comment]
I'm curious why you've closed this. SHA1 is definitely a weak algorithm. Chrome already displays SSL certs hashed with SHA1 as completely insecure, provided their date of expiration is after January 1st 2017.

**Comment by craigcarnell** [comment]
@Orvid It was because my puppet module was trying to load trusty (14.04) onto 16.04. I updated my module to use lsbreleasename instead to fix it.

**Comment by scfc** [comment]
This still shows up in each Travis CI run that invokes `apt-get update` (cf. for example https://travis-ci.org/ejmr/php-mode/jobs/273720248, line 578), so if this could be dealt with at HHVM's end that would be very much appreciated.

https://wiki.debian.org/Teams/Apt/Sha1Removal#Fixing_half-broken_repositories has some information about an upgrade path that does not require user interaction.  (Personally, I prefer key changes & Co. to not happen behind the scenes.)
