### ISSUE TITLE
No Trusty nightly packages since 2016.10.03

### ISSUE THREAD

**Issue by fredemmott** [hhvm/packaging#147]

**Comment by fredemmott** [comment]
If this is intentional, hhvm-docker will need changing to use a more recent ubuntu for future HHVM releases

**Comment by fredemmott** [comment]
Also, recent versions of HHVM are only supported on Travis if using Trusty.

**Comment by fredemmott** [comment]
Bump. cc @paulbiss , @mofarrell ; no 3.17 packages either.

**Comment by mofarrell** [comment]
@fredemmott Looks like we do have a 3.17 package for trusty.  But the nightlies are not there.

**Comment by fredemmott** [comment]
Whoops :/ I'll go file an issue over at hhvm-docker then :)

**Comment by fredemmott** [comment]
@mofarrell AIUI this is a wontfix?

**Comment by mofarrell** [comment]
All the build infrastructure is being reworked.  Once we have a little more stability we will do the nightly builds properly.  Since 3.18 is the last version that is going to run on Trusty, this is a wontfix.  For all the other supported systems, nightly builds will be built properly soon.

**Comment by fredemmott** [comment]
Reworked again - fixed in new WIP nightly system (see https://github.com/hhvm/packaging/issues/128#issuecomment-342037825 )
