### ISSUE TITLE
Replace 'Maintainer: Paul Tarjan' with a current member of the team, or some group contact method

### ISSUE THREAD

**Issue by fredemmott** [hhvm/packaging#148]

**Comment by simonwelsh** [comment]
So long as this doesn't involve losing trailing comma support :p

**Comment by jwatzman** [comment]
The GPG key used to sign the apt repos also has his name/email encoded into it. This can be updated without changing the key, though it obviously doesn't retroactively update people who have already imported it into their apt keyrings.
