### ISSUE TITLE
Cosmic (Ubuntu 18.10) packaging?

### ISSUE THREAD

**Issue by craigcarnell** [hhvm/packaging#168]
I can't see it in https://dl.hhvm.com/ubuntu/dists/

**Comment by fredemmott** [comment]
- [ ] add build configuration
- [ ] add nightly builds
- [ ] add latest release builds after nightly builds are stable
- [ ] investigate cherry-picking support to 3.27

**Comment by fredemmott** [comment]
#  create apt repository configuration

1. create an ubuntu 14.04 instance in us-west-2a (*must* be 2a, or can't mount EBS). Select us-west-2a by selecting subnet
1. attach EBS from AWS control panel
1. `mkdir /mnt/dl.hhvm.com; mount /dev/xvdf /media/dl.hhvm.com`
1. `apt update`
1. `apt install -y reprepro awscli`
1. Decrypt and import the gpg key with something similar to ` aws kms decrypt --ciphertext-blob "fileb://$(pwd)/gpg-key.kms-ciphertext" --query Plaintext --output text | base64 -d | gpg --import`
1. `gpg --export-secret-keys -a | gpg2 --import`
1. Update `/media/dl.hhvm.com/ubuntu/conf/distributions`
1. In `/media/dl.hhvm.com/ubuntu/` run `reprepro export <distroname>` eg `reprepro export <bionic>`
1. unmount and unattach the EBS volume
1. run the package build script

**Comment by fredemmott** [comment]
# manually trigger a build of yesterday's nightly

`bin/make-package-on-aws 2018.10.26 cosmic`

Unfortunately, on the build worker:

```
$ tail -f /var/log/hhvm-build
Unsupported distro: cosmic
```

**Comment by fredemmott** [comment]
- repo now exists and has yesterday's nightly
- added cosmic to automated nightly builds
- if those go well over the weekend, will do release build on Monday

**Comment by fredemmott** [comment]
3.29 now has a cosmic build

**Comment by fredemmott** [comment]
Unlikely to add 3.27 support for cosmic; too much time pressure for other stuff that needs to be done before 3.30 to spend time on that now.
