### ISSUE TITLE
Ubuntu Bionic hhvm-dev package missing hphpize binary

### ISSUE THREAD

**Issue by na2axl** [hhvm/packaging#219]
Ubuntu Bionic hhvm-dev package missing hphpize binary. I've installed hhvm-dev (4.30.0-1~bionic) but I'm not able to use hphpize in command line. I'm always getting the error:
```
The command « hphpize » was not found, but can be installed with :

sudo apt install hhvm-dev
```

**Comment by fredemmott** [comment]
merging into #163
