### ISSUE TITLE
no debian builds published on 2019-11-16 nightlies, despite most platforms succeeding

### ISSUE THREAD

**Issue by fredemmott** [hhvm/packaging#220]
debian-8 failed, but other debs should still have been published

**Comment by fredemmott** [comment]
re-running these with a fix for debian 8 (upgraded cmake version)

Also, state machine from the original run has no output

**Comment by jjergus** [comment]
```
cannot publish because there are unbuilt packages: debian-8-jessie
```

Is it safe to run the publish script if not all builds succeeded? It's trivial to remove that check but I wasn't sure if it's safe.

> Also, state machine from the original run has no output

AWS doesn't allow output on failures. There is a list of what failed inside the exception message, and the full output is available as input to the last step. I'll write some scripts to print out the correct thing nicely in each case.

**Comment by fredemmott** [comment]
> Is it safe to run the publish script if not all builds succeeded? It's trivial to remove that check but I wasn't sure if it's safe.

I think so; we've definitely done that frequently on the old system.

As long as the docker image doesn't depend on a failed build, we still get a lot of value out of it from the travis runs of our hack code
