### ISSUE TITLE
Provide more detailed installation/test/deploy instructions for python lambdas

### ISSUE THREAD

**Issue by fredemmott** [hhvm/packaging#236]
ModuleNotFoundError: No module named 'boto3'

**Comment by jjergus** [comment]
There are some instructions here: https://github.com/hhvm/packaging/tree/master/aws/hhvm1#lambda-functions

I'll add something about dependencies there. Anything else missing?

**Comment by jjergus** [comment]
https://github.com/hhvm/packaging/commit/69063ceb0b4be6407a6df825f80dc5fb4fbb27c0

**Comment by fredemmott** [comment]
Heh, FB managed macs appear to be very unfriendly to this:

```
% pip
zsh: /opt/homebrew/bin/pip: bad interpreter: /opt/homebrew/opt/python35/bin/python3.5: no such file or directory
```

... and FB claims ownership of /usr/local/bin so brew link fails. Will dig in later.

**Comment by jjergus** [comment]
If you're doing a simple change that doesn't need testing (like the one today), you can also ignore the failure, the deploy.sh script should ask you if you want to do that.

**Comment by fredemmott** [comment]
Sorry, yep, I saw error and ^C'd without reading the last line D:
