### ISSUE TITLE
ArchLinux Build conflicts with libzip  

### ISSUE THREAD

**Issue by nicodoggie** [hhvm/packaging#24]
The build succeeds but fails installation:

```
error: failed to commit transaction (conflicting files)
hhvm: /usr/include/zip.h exists in filesystem
hhvm: /usr/include/zipconf.h exists in filesystem
hhvm: /usr/lib/libzip.so exists in filesystem
Errors occurred, no packages were upgraded.
```

It's possible to force overwrite, but it may break everything libzip depends on.

**Comment by fredemmott** [comment]
@mofarrell : afaict Facebook doesn't maintain arch packages, this is entirely by the arch commuinty on their infra (AUR?), and this should be closed?

**Comment by mofarrell** [comment]
We don't maintain support for it.  I believe that someone at FB may have set it up originally, but I don't believe we ever packaged binaries for it.
