### ISSUE TITLE
Bad paths (typo of PGKROOT/PKGROOT, lib/lib) in debs

### ISSUE THREAD

**Issue by fredemmott** [hhvm/packaging#249]
https://github.com/facebook/hhvm/issues/8769

cc @IngwiePhoenix

**Comment by fredemmott** [comment]
@IngwiePhoenix That should have the PKGROOT issue fixed in the next round of packages; your paste also included `lib/lib`, which is more subtle, so I want to test more thoroughly before merging

**Comment by IngwiePhoenix** [comment]
Huh, you're right. I guess I must've overlooked that. Do you have a guess as to when I can expect the fixed debs to show up on the repositories?

**Comment by fredemmott** [comment]
It'll start with tomorrow's nightly builds; if those are good, at least 4.87, but we should backport these two fixes to past releases - best case would be wednesday

**Comment by fredemmott** [comment]
Fixed in the nightlies; FYI these are only in the '-dev' packages, which are:
- only required if plannign to work on a dynamically loadable HHVM extension
- not well tested, and likely broken

You don't need them to run/develop code written in Hack
