### ISSUE TITLE
Missing hphp/system/constants.h from hhvm-dev-nightly

### ISSUE THREAD

**Issue by jaredkipe** [hhvm/packaging#68]
Missing hphp/system/constants.h from hhvm-dev-nightly

**Comment by doublecompile** [comment]
It seems like a missing `constants.h` causes a blocker when building the MongoDB HHVM extension. See 10gen-labs/mongo-hhvm-driver-prototype#22

**Comment by doublecompile** [comment]
Specifically, I can't compile MongoDB's HHVM extension because HHVM's `hphp/runtime/base/timezone.h` has the line:
```c++
#include "hphp/system/constants.h"
```

**Comment by jwatzman** [comment]
Something weird is going on; `hphp/system/CMakeLists.txt` is supposed to include `constants.h` in the install, which it does appear to do in my test box. I'm doing a full build on an Ubuntu 14.04 machine right now to play with it -- the file is definitely missing in the debs. (And the deb builder just copies that dir, AFAICT. So not sure where it's getting lost.)

**Comment by jwatzman** [comment]
Derp, no wonder I couldn't repro, this is fixed in master but not 3.8 (https://github.com/facebook/hhvm/commit/f7bc43f9498b83dbdb2e874f1dc0cc1a4d840ca5) -- I'll pick that.

**Comment by jwatzman** [comment]
Picked as https://github.com/facebook/hhvm/commit/dd809d6fcaf64dc4a32bac93f83922dd57a5b7f8
