### ISSUE TITLE
Error on reading gpg keys

### ISSUE THREAD

**Issue by JohanTan** [hhvm/packaging#78]
I was running package on Ubuntu 14.04 (trusty) with command: 
`./package ubuntu trusty 3.3.0`.

However, here is what I got:

-- Installing header files for hhbc
-- Installing header files for neo
-- Installing header files for parser
-- Installing header files for runtime
-- Installing header files for ext
-- Installing header files for ext_zend_compat
-- Installing header files for system
-- Installing header files for util
-- Installing header files for vixl
-- Installing header files for vixl
-- Installing header files for zend
-- Installing: /tmp/tmp.oG9SrRhU9b/usr/bin/hhvm
-- Installing header files for hhvm
-- Installing: /tmp/tmp.oG9SrRhU9b/usr/bin/hphpize
-- Installing: /tmp/tmp.oG9SrRhU9b/usr/lib/x86_64-linux-gnu/hhvm/hphpize/hphpize.cmake
Checking version
Packaging HHVM in /tmp/tmp.EDtcrOTA6n
finished creating hhvm package contents
dpkg-deb: building package `hhvm' in`hhvm_3.3.0~trusty_amd64.deb'.
Processing /tmp/tmp.EDtcrOTA6n/hhvm_3.3.0~trusty_amd64.deb...
gpg: error reading key: public key not found
gpg: no default secret key: secret key not available
gpg: /tmp/debsigs-ng.Gkma0j/digests: clearsign failed: secret key not available
E: Signing failed. Error code: 512

Not sure what went wrong

**Comment by fredemmott** [comment]
Sorry, I missed this at the time :(

Closing:
 - no, this shouldn't be ran outside of facebook
 - once the ng/ directory is used instead, this won't matter - it's separating the signing from the building
