### ISSUE TITLE
install from centos6.5 repo, hhvm doesn't have hphpize

### ISSUE THREAD

**Issue by wudikua** [hhvm/packaging#80]
Using yum install hhvm, and hhvm --version is hhvm-dev 3.3,howerver there is no hphpize tools

**Comment by singhupendra** [comment]
same issue here. Installed hhvm using  https://github.com/facebook/hhvm/wiki/Prebuilt-packages-on-Centos-6.5.

**Comment by jwatzman** [comment]
From the page you linked:

> These are unofficial community-provided packages not supported by the HHVM team

That said, the page looks like it might pull from Fedora, so this *might* be the same packages that @jrobeson has been working on, so you *might* have luck seeing if he can comment here or otherwise help you?
