### ISSUE TITLE
session.save_path set for debian in /etc/hhvm/php.ini is not created by package

### ISSUE THREAD

**Issue by bd808** [hhvm/packaging#81]
The default [/etc/hhvm/php.ini](https://github.com/hhvm/packaging/blob/9bd53edcfd853efc65fe0062c7f5f5bdd73b5079/hhvm/deb/skeleton/etc/hhvm/php.ini#L3) configures hhvm to use /var/lib/php5 as the session save path, but nothing in the package causes this directory to be created. This is causing a [MediaWiki unit test failure](https://travis-ci.org/wikimedia/mediawiki/jobs/40335649#L120-L126) on Travis when the hhvm-nightly build is used.

I'm not sure what the right fix for this is in the Debian packaging world. Having two discrete packages manage the same directory is a sticky problem. The Debian package for php5-common includes a [post-rm script](http://anonscm.debian.org/cgit/pkg-php/php.git/tree/debian/php5-common.postrm.extra) that force deletes the /var/lib/php5 directory. I'd guess the most proper way to ensure that this directory is created would be by having the HHVM package depend on the php5-common package.

**Comment by soulteary** [comment]
my hhvm version is `HipHop VM 3.4.2 (rel)`, still has this problem.  even i thought is not a matter.

**Comment by Majkl578** [comment]
They should use pkg/debian/dirs file to list additional directories.
https://www.debian.org/doc/manuals/maint-guide/dother.en.html#dirs

**Comment by jimmyyem** [comment]
I have a proble in Windows7. I changed session.save_path   from  D:/wamp/tmp to 2;D:/wamp/tmp  
But after I restart Apache there is no folder in D:/wamp/tmp  
Did I do something wrong?

**Comment by jwatzman** [comment]
@jimmyyem this is a different issue. Also, given that you are running on Windows, you are almost certainly not using HHVM and are very much in the wrong place :)
