### ISSUE TITLE
Ubuntu trusty nightly PPA hasn't built in 4 days

### ISSUE THREAD

**Issue by joshuataylor** [hhvm/packaging#88]
http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-amd64/Packages shows "hhvm-nightly_2014.12.11~trusty_amd64.deb"

**Comment by xingzhiyuan** [comment]
when i updated with apt-get install gawk, then make it ,the error is still exist.

**Comment by jwatzman** [comment]
If the file was generated improperly, your build will still be broken. Try `git clean -dxf && cd third-party && git clean -dxf` to start over.
