### ISSUE TITLE
Mark config files as config files so they aren't overwritten on upgrade

### ISSUE THREAD

**Issue by r3wt** [hhvm/packaging#90]
https://github.com/facebook/hhvm/issues/4457

**Comment by jwatzman** [comment]
This might be fixed by https://github.com/hhvm/packaging/commit/5ebd2b52f9d26b81d5a25fed80fe26cc6fe099b9?

**Comment by liayn** [comment]
Will check with the next update. Thanks.

**Comment by jwatzman** [comment]
I've just updated the checkout on the build machine so the next nightlies (in 12 hours or so) will have the updates.

**Comment by fredemmott** [comment]
Closing, should have been fixed by that, and if not, by new WIP nightly system (see https://github.com/hhvm/packaging/issues/128#issuecomment-342037825 )
