### ISSUE TITLE
Can't install hhmv on debian jessie because of libjpeg8

### ISSUE THREAD

**Issue by willdurand** [hhvm/packaging#96]
Quoted from https://github.com/facebook/hhvm/issues/4616: 

> Prebuilded hhvm package depends on libjpeg8, but there no such package in jessie anymore, cause debian is migrating to libjpeg-turbo.
>
> As you can see - https://packages.debian.org/jessie/libjpeg8
>
>     apt-get install hhvm-nightly
>     Reading package lists... Done
>     Building dependency tree       
>     Reading state information... Done
>     Some packages could not be installed. This may mean that you have
>     requested an impossible situation or if you are using the unstable
>     distribution that some required packages have not yet been created
>     or been moved out of Incoming.
>     The following information may help to resolve the situation:
>
>     The following packages have unmet dependencies:
>     hhvm-nightly : Depends: libjpeg8 but it is not installable
>     E: Unable to correct problems, you have held broken packages.
>
> On existing installations i still have libjpeg8, but on fresh servers it's a problem.

**Comment by jwatzman** [comment]
#95 reported this issue but said it went away. I guess `libjpeg8` is gone for good now? I'm kicking off a test build to see if `libjpeg-turbo` can be a drop-in replacement.

**Comment by jwatzman** [comment]
Fixed in the build scripts. Any nightly dated Jan 14 or later should have it. (But nightlies are currently broken due to a version number change, and it could take me a day or two to get it fixed and landed.)

**Comment by Mte90** [comment]
There is an another problem `libunwind7` not exist in jessie the correct package is https://packages.debian.org/sid/libunwind8.
Also for libboost-regex1.49.0, the correct package https://packages.debian.org/sid/libboost-regex1.55.0 or https://packages.debian.org/sid/libboost-regex1.54.0

**Comment by Majkl578** [comment]
@Mte90: Open new issue for that.

**Comment by jesus0alejo** [comment]
https://www.lwks.com/index.php?option=com_kunena&func=view&catid=217&id=103501&Itemid=81 
En el último comentario está el enlace para descargar el paquete libjepg8 y funciona en debian jessie.
In last commentary is the link to download the package libjepg8 and work in debian jessie. Greetings from Venezuela.
