### ISSUE TITLE
Ubuntu trusty nightly PPA hasn't built since hhvm-nightly_2015.01.11~trusty_amd64

### ISSUE THREAD

**Issue by joshuataylor** [hhvm/packaging#97]
Seems it's stuck,

http://dl.hhvm.com/ubuntu/dists/trusty/main/binary-amd64/Packages shows "hhvm-nightly_2015.01.11~trusty_amd64.deb"

**Comment by jwatzman** [comment]
Yep, the packaging script version detection is broken, I have a patch out to fix it. I'll try to get it in ASAP.

**Comment by jwatzman** [comment]
I'm gonna manually reroll trusty now to make sure it builds.

**Comment by joshuataylor** [comment]
Seems it's building now: 2015.01.14~trusty is pulled in via apt.

**Comment by jwatzman** [comment]
Yep, they normally run from midnight-11am Pacific, but I forced that one to run while I could monitor it. The rest should rebuild tonight.
