### ISSUE TITLE
Wrong dependency debian jessie

### ISSUE THREAD

**Issue by Mte90** [hhvm/packaging#98]
There is an another problem libunwind7 not exist in jessie the correct package is https://packages.debian.org/sid/libunwind8.
Also for libboost-regex1.49.0, the correct package https://packages.debian.org/sid/libboost-regex1.55.0 or https://packages.debian.org/sid/libboost-regex1.54.0

Ref: #96

**Comment by jwatzman** [comment]
Where are you seeing these deps? The control file I have for jessie looks correct, including boost 1.55 and libunwind8: https://github.com/hhvm/packaging/blob/9ebc5150c53d898abca38eb1273b30343a07357c/hhvm/deb/jessie/DEBIAN/control

**Comment by Mte90** [comment]
Uhm ok this a problem of my system that not detect the jessie package.
Sorry for the ticket
