### ISSUE TITLE
Compile with LibYaml

### ISSUE THREAD

**Issue by SiebelsTim** [hhvm/packaging#99]
Looks like prebuilt packages are missing this. (see https://github.com/facebook/hhvm/issues/4387#issuecomment-70695174).

**Comment by jwatzman** [comment]
Isn't it on by default? https://github.com/facebook/hhvm/blob/master/CMake/Options.cmake#L25 And AFAICT the packaging script doesn't turn it off?

**Comment by jwatzman** [comment]
Yeah, I pulled `CMakeCache.txt` from some random build on the 14.04 build VM, and found `ENABLE_ZEND_COMPAT:BOOL=ON`.

**Comment by df2** [comment]
Okay excellent-- I had not upgraded the repository to 'utopic' and that upgrade made the difference.

**Comment by jwatzman** [comment]
What were you using before? I wasn't aware of any distro-specific dependencies here.

**Comment by df2** [comment]
trusty. Have not had any issues before this. Could it be due to installing libyaml after hhvm, and a reinstall not picking up on it but a distro upgrade did? Installed libyaml-dev also and hadn't tried reinstalling the original binary after that.

**Comment by SiebelsTim** [comment]
I'm running 14.04. It's not about zend_compat though. I just checked with `easter_date`. That works perfectly.
However yaml does not. It works with my local build. So this might still be an issue.

**Comment by jwatzman** [comment]
Aha, the utopic VM had `libyaml-dev` installed (and somehow also ended up with the right libyaml in the library deps for the deb), but the trusty VM did not. Fixing that now, any new trusty builds should also have yaml.

**Comment by SiebelsTim** [comment]
Great! Thanks :)
